[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
notes = "Fkswxi1MmPoHJMnG1AiYubb8WpMDBSLZ1o88aZhjJW5v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 60
shutdown_wait = 2000
upgradeable = false
